[main]
# Invert axis in move panel. Default is False. Change to true to invert
invert_x: False
invert_y: False
invert_z: True

# Time (seconds) before the Job Status page reverts to main menu after a successful job
job_complete_timeout: 300

# Time (seconds) before the Job Status page reverts to main menu after a successful job.
#   If this option is 0, the user must click on a button to go back to the main menu.
job_error_timeout: 0

# [preheat PETG]
# # Temperature for the heated bed
# bed: 75
# # Temperature for the tools
# extruder: 235

